import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import type { Request, Response } from "express";
import { TOOL_DEFS, type ToolCtx } from "../tools/index.js";
import { OpsError, toolErrorPayload, loggableError } from "../lib/errors.js";
import { audit } from "../audit/audit.js";

function createServer(ctx:ToolCtx):McpServer{const server=new McpServer({name:"remote-ops-mcp",version:"1.1.0"},{instructions:"Servidor de operações remotas READ-ONLY em VPS Linux. Sempre descubra os alvos com targets_list antes de usar. Os parâmetros 'target' devem ser IDs do registry (ex.: wandora-prod) — NUNCA IPs, usuários ou credenciais. Todas as ações são somente leitura e auditadas."});
 for(const def of TOOL_DEFS){server.registerTool(def.name,{description:def.description,inputSchema:def.inputSchema,_meta:{securitySchemes:[{type:"oauth2",scopes:["mcp:read"]}]},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async(args:Record<string,unknown>)=>{const started=Date.now();const base={ts:new Date().toISOString(),request_id:ctx.requestId,actor:ctx.actor,target:typeof(args as Record<string,unknown>)?.target==="string"?(args as Record<string,string>).target:undefined,tool:def.name,mutation:false};try{const result=await def.run(args??{},ctx);audit({...base,duration_ms:Date.now()-started,result:"ok"});return{content:[{type:"text" as const,text:JSON.stringify(result,null,2)}]};}catch(err){if(!(err instanceof OpsError))console.error(JSON.stringify({ts:new Date().toISOString(),level:"error",msg:"tool_crash",tool:def.name,error:loggableError(err)}));const{payload,denied}=toolErrorPayload(err);audit({...base,duration_ms:Date.now()-started,result:denied?"denied":"error",error_code:payload.error.code});return{content:[{type:"text" as const,text:JSON.stringify(payload,null,2)}],isError:true};}});}
 return server;}
export async function handleMcpRequest(req:Request,res:Response):Promise<void>{const ctx:ToolCtx={actor:(req as Request&{actor?:string}).actor??"anonymous",requestId:(req as Request&{requestId?:string}).requestId??"unknown"};const server=createServer(ctx);const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});res.on("close",()=>{void transport.close();void server.close();});await server.connect(transport);await transport.handleRequest(req,res,req.body);}