import crypto from "node:crypto";
import fs from "node:fs";
import { Client as SshClient, type ClientChannel } from "ssh2";
import { env } from "../lib/env.js";
import { OpsError } from "../lib/errors.js";
import { buildRemoteCommand } from "../lib/quote.js";
import type { TargetConfig } from "../config/targets.js";

export interface ExecResult { code:number|null; stdout:string; stderr:string; durationMs:number; truncated:boolean; timedOut:boolean; }
export interface ExecOptions { timeoutMs?:number; maxBytes?:number; }
interface Pooled { client:SshClient; lastUsed:number; }
const pools=new Map<string,Pooled>();
interface Semaphore { active:number; queue:Array<()=>void>; }
const semaphores=new Map<string,Semaphore>();
async function withSlot<T>(targetId:string,fn:()=>Promise<T>):Promise<T>{let sem=semaphores.get(targetId);if(!sem){sem={active:0,queue:[]};semaphores.set(targetId,sem);}if(sem.active>=env.PER_TARGET_CONCURRENCY)await new Promise<void>((resolve)=>sem!.queue.push(resolve));sem.active++;try{return await fn();}finally{sem.active--;const next=sem.queue.shift();if(next)next();}}
function loadPrivateKey(t:TargetConfig):string{const raw=(()=>{if(t.keyFile){try{return fs.readFileSync(t.keyFile,"utf8");}catch{throw new OpsError("SSH_UNAVAILABLE",`keyFile "${t.keyFile}" não pôde ser lido para o target "${t.id}"`,`monte o volume ./secrets e confira o caminho no targets.json`);}}if(t.credentialRef){const v=process.env[t.credentialRef];if(v)return v.replace(/\\n/g,"\n");}throw new OpsError("SSH_UNAVAILABLE",`credencial SSH não configurada para o target "${t.id}"`,`defina keyFile (recomendado) ou credentialRef no targets.json`);})();if(!raw.includes("PRIVATE KEY"))throw new OpsError("SSH_UNAVAILABLE",`credencial do target "${t.id}" não é uma private key PEM válida`,`confira o arquivo montado em secrets/ (formato OpenSSH/PEM)`);return raw;}
function hostKeyMatches(presented:Buffer,t:TargetConfig):boolean{if(t.hostKeyFingerprint){const fp="SHA256:"+crypto.createHash("sha256").update(presented).digest("base64").replace(/=+$/,"");if(fp===t.hostKeyFingerprint)return true;}if(t.hostKey){const clean=t.hostKey.replace(/\s+/g,"");if(presented.toString("base64")===clean)return true;}return false;}
interface ConnectOptsWithVerifier{hostVerifier?:(key:Buffer,verify?:(ok:boolean)=>void)=>boolean|void;}
function ensureConnected(t:TargetConfig):Promise<SshClient>{const existing=pools.get(t.id);if(existing){existing.lastUsed=Date.now();return Promise.resolve(existing.client);}const client=new SshClient();const privateKey=loadPrivateKey(t);const connectTimeout=t.connectTimeoutMs??env.CONNECT_TIMEOUT_MS;const ready=new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{try{client.end();}catch{}reject(new OpsError("SSH_UNAVAILABLE",`timeout conectando ao target "${t.id}"`));},connectTimeout);client.once("ready",()=>{clearTimeout(timer);resolve();});client.once("error",(err:Error)=>{clearTimeout(timer);pools.delete(t.id);const mismatch=(client as unknown as{__hostKeyMismatch?:boolean}).__hostKeyMismatch;const msg=mismatch?`host key do target "${t.id}" NÃO confere com o fingerprint configurado`:`falha SSH no target "${t.id}": ${err.message}`;reject(new OpsError(mismatch?"HOST_KEY_MISMATCH":"SSH_UNAVAILABLE",msg,mismatch?"se o servidor foi realmente recriado, atualize hostKeyFingerprint no targets.json":"verifique rede/credenciais e se o host está no ar"));});client.on("close",()=>pools.delete(t.id));});
try{client.connect({host:t.host,port:t.port,username:t.username,privateKey,readyTimeout:connectTimeout,keepaliveInterval:15_000,keepaliveCountMax:3,hostVerifier:((key:Buffer)=>{const ok=hostKeyMatches(key,t);if(!ok){(client as unknown as{__hostKeyMismatch?:boolean}).__hostKeyMismatch=true;return false;}return true;}) as ConnectOptsWithVerifier["hostVerifier"]});}catch(e){throw new OpsError("SSH_UNAVAILABLE",`falha ao iniciar conexão com o target "${t.id}": ${(e as Error).message}`);}return ready.then(()=>{pools.set(t.id,{client,lastUsed:Date.now()});return client;});}
export async function sshExec(t:TargetConfig,argv:string[],opts?:ExecOptions):Promise<ExecResult>{return withSlot(t.id,async()=>{const client=await ensureConnected(t);const cmd=buildRemoteCommand(argv);const timeoutMs=opts?.timeoutMs??t.commandTimeoutMs??env.COMMAND_TIMEOUT_MS;const maxBytes=opts?.maxBytes??env.MAX_OUTPUT_BYTES;const started=Date.now();return await new Promise<ExecResult>((resolve,reject)=>{client.exec(cmd,(err:Error|undefined,stream:ClientChannel|undefined)=>{if(err||!stream){reject(new OpsError("SSH_UNAVAILABLE",`exec falhou no target "${t.id}": ${err?.message??"sem stream"}`));return;}const ch=stream as unknown as ClientChannel&{stderr:NodeJS.ReadableStream};let out:Buffer=Buffer.alloc(0),errBuf:Buffer=Buffer.alloc(0),truncated=false,timedOut=false;const append=(buf:Buffer,chunk:Buffer,cap:number):Buffer=>{if(buf.length>=cap){truncated=true;return buf;}if(buf.length+chunk.length>cap){truncated=true;return Buffer.concat([buf,chunk.subarray(0,cap-buf.length)]);}return Buffer.concat([buf,chunk]);};const timer=setTimeout(()=>{timedOut=true;try{stream.close();}catch{}},timeoutMs);stream.on("data",(c:Buffer)=>{out=append(out,c,maxBytes);});ch.stderr.on("data",(c:Buffer)=>{errBuf=append(errBuf,c,Math.min(maxBytes,65_536));});stream.on("close",(code:number|null)=>{clearTimeout(timer);if(timedOut){reject(new OpsError("COMMAND_TIMEOUT",`comando excedeu ${timeoutMs}ms no target "${t.id}"`,`binário: ${argv[0]}`));return;}resolve({code,stdout:out.toString("utf8"),stderr:errBuf.toString("utf8"),durationMs:Date.now()-started,truncated,timedOut});});});});});}
export function closeTargetPool(targetId:string):void{const pooled=pools.get(targetId);if(!pooled)return;try{pooled.client.end();}catch{}pools.delete(targetId);}
export function closeAllPools():void{for(const[id,p]of pools){try{p.client.end();}catch{}pools.delete(id);}}
export function startIdleSweeper():NodeJS.Timeout{const timer=setInterval(()=>{const now=Date.now();for(const[id,p]of pools){if(now-p.lastUsed>5*60_000){try{p.client.end();}catch{}pools.delete(id);}}},60_000);timer.unref();return timer;}
