/** Defense-in-depth redaction applied to all tool output. */
const REDACTED="[REDACTED]";
const TEXT_PATTERNS:RegExp[]=[/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g,/\bAKIA[0-9A-Z]{16}\b/g,/\b(?:(?:aws)?_?access_?key_?id|aws_?secret_?access_?key)\b\s*[:=]\s*["']?[A-Za-z0-9/+=]{8,}/gi,/\beyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\b/g,/\bsbp_[A-Za-z0-9]{16,}\b/g,/\bsk-[A-Za-z0-9_-]{16,}\b/g,/\bsk-proj-[A-Za-z0-9_-]{16,}\b/g,/\bghp_[A-Za-z0-9]{16,}\b/g,/\bgho_[A-Za-z0-9]{16,}\b/g,/\bgithub_pat_[A-Za-z0-9_]{16,}\b/g,/\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g,/\bAIza[A-Za-z0-9_-]{20,}\b/g,/\bYA29\.[A-Za-z0-9_-]{20,}\b/g,/\bBearer\s+[A-Za-z0-9._~-]{10,}/gi,/\bBasic\s+[A-Za-z0-9+/=]{16,}/gi,/\b(?:password|passwd|pwd|secret|token|api[_-]?key|apikey|access[_-]?token|refresh[_-]?token|client[_-]?secret|private[_-]?key|service[_-]?role[_-]?key|anon[_-]?key)\b\s*[:=]\s*["']?[^\s"'`]{4,}/gi,/\b(?:postgres(?:ql)?|mysql|mariadb|mongodb(?:\+srv)?|redis|rediss|amqps?):\/\/[^:\s/@]+:[^@\s/]+@/gi,/^\s*[A-Z0-9_]*(?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL)[A-Z0-9_]*\s*=\s*\S+$/gim];
export function redactText(text:string):string{let out=text; for(const p of TEXT_PATTERNS) out=out.replace(p,REDACTED); return out;}
const SENSITIVE_KEY_NAMES=new Set(["env","environment","password","passwd","secret","secrets","token","tokens","authorization","auth","authconfig","apikey","api_key","clientsecret","client_secret","privatekey","private_key","credential","credentials","registryconfig"]);
const SENSITIVE_TOKENS=new Set(["env","environment","password","passwd","secret","secrets","token","tokens","credential","credentials","apikey","key","keys","auth","authorization","privatekey","cookie"]);
function keyIsSensitive(key:string):boolean{const norm=key.toLowerCase(); if(SENSITIVE_KEY_NAMES.has(norm.replace(/[^a-z_]/g,""))) return true; return norm.split(/[^a-z0-9]+/).filter(Boolean).some((tk)=>SENSITIVE_TOKENS.has(tk));}
export function redactObject<T>(value:T):T{return deepRedact(value,0) as T;}
function deepRedact(value:unknown,depth:number):unknown{if(depth>12)return"[MAX_DEPTH]"; if(typeof value==="string")return redactText(value); if(Array.isArray(value))return value.map((v)=>deepRedact(v,depth+1)); if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>)){out[k]=keyIsSensitive(k)?(Array.isArray(v)?`[${v.length} valores redigidos]`:REDACTED):deepRedact(v,depth+1);}return out;} return value;}
